### ISSUE TITLE
Bug: Very Tiny non-issue lines on primary,secondary, or duel roads. 

### ISSUE THREAD

**Issue by Korgi2** [facebookmicrosites/Open-Mapping-At-Facebook#10]
Bug: Very Tiny non-issue lines on primary,secondary, or duel roads. 

RapID File database has a large amount of roads that don't seem to exist or are just diagonal lines in multi-lane roads:

Examples:
![image](https://user-images.githubusercontent.com/61196219/74764700-30559d80-5250-11ea-9732-bf13ad90a51b.png)
![image](https://user-images.githubusercontent.com/61196219/74764718-3b103280-5250-11ea-8921-efeff7a5336a.png)
![image](https://user-images.githubusercontent.com/61196219/74764738-43686d80-5250-11ea-96a8-acff16c64c11.png)

**Comment by jeffdefacto** [comment]
Hi @Korgi2 

Thanks for the feedback.

Yeah, these have been a difficult data error to solve on wide highways. Typically, these roads are already mapped and conflated away, but the width can make some small incorrect vectors generate as the prediction is much wider than the OSM vector.

Example prediction

![image](https://user-images.githubusercontent.com/17914981/74769561-7d7d4380-523f-11ea-90fc-13b8a55a016a.png)

**Comment by Korgi2** [comment]
Does the AI also by chance work off of implied lines because I see it like to try and continue a road even if it means running through buildings. A bit humorous but confusing.

![image](https://user-images.githubusercontent.com/61196219/74790515-c48e2780-5285-11ea-920f-b788dc3e9e22.png)
![image](https://user-images.githubusercontent.com/61196219/74790529-cfe15300-5285-11ea-947d-06add396d382.png)

**Comment by jeffdefacto** [comment]
The ML can infer connections incorrectly some times, it's certainly not perfect, but it could also be an error in the vectorization process.

Can you supply the location of those examples? I can take a look at these cases.

**Comment by Korgi2** [comment]
Not one of the examples I posted but one that shows up in the data I downloaded is at -80.3087616, 25.7200847 and another -80.3062585, 25.7268225.

**Comment by jeffdefacto** [comment]
Thanks for the examples. These are definitely poor quality ML. The good news is that the US is still using an older prediction model and will be refreshed to higher quality data in the near future.

Here are the old and new predictions for those locations. As you can see the new result is far better.

Old prediction
![image](https://user-images.githubusercontent.com/17914981/74871887-1334d380-5311-11ea-9d3e-f454bbf9d44f.png)

New prediction
![image](https://user-images.githubusercontent.com/17914981/74871922-25167680-5311-11ea-9fcb-e6cfb3dc4b91.png)

Old prediction
![image](https://user-images.githubusercontent.com/17914981/74871938-2ba4ee00-5311-11ea-8ce5-3b7b640ee3c4.png)

New prediction
![image](https://user-images.githubusercontent.com/17914981/74871953-31023880-5311-11ea-841e-3d1924be22e7.png)

Thanks again for the feedback.

**Comment by Korgi2** [comment]
Alright cool. It's nice to see that the prediction software is still being updated.
