### ISSUE TITLE
update Wiki

### ISSUE THREAD

**Issue by michael63-osm** [facebookmicrosites/Open-Mapping-At-Facebook#16]
**Title:** update Wiki

#
**Description:**

If the wiki is to be considered the main guide to mapping with AI then it should be updated.

MapWithAi projects are common on the production instance of the HOT Tasking Manager which is version 4 while the wiki describes the old interface of version 3 which was (and is) used on the staging site for ai-assisted mapping..

The JOSM preferences panel has been reorganized a few months ago and looks different from the one described in the wiki.

**Comment by jeffdefacto** [comment]
Hey @michael63-osm. I just gave the wiki a refresh.

Thanks for reminding us to give it an update!
