### ISSUE TITLE
Landure Areas with No transparent covering (Partial and Total)

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookmicrosites/Open-Mapping-At-Facebook#17]
**Title:**Landuse areas are now depicted with a non transparent patern, this is not happening in ID just in RapID

#
**Files:** 

![Screenshot 2021-02-25 14 12 21](https://user-images.githubusercontent.com/22849578/109198815-0abd7700-7775-11eb-8072-88281ebbaf55.png)
![Screenshot 2021-02-25 14 12 49](https://user-images.githubusercontent.com/22849578/109198819-0c873a80-7775-11eb-8f22-701b32fad130.png)

#
**Description:**

This landcover patern is not transparent anymore and seems to be real weird

**Comment by jeffdefacto** [comment]
Hi @jjiglesiasg 

I can't reproduce this. Can you try to clear your RapiD cache and see if it fixes itself. You can do this with ctl+shift+r while on the page.

Let us know if that resolves it. If not, we'll dig deeper.

**Comment by jjiglesiasg** [comment]
Cleared the RapiD cache and it work fine now. thanks

Item could be closed. I guess
