### ISSUE TITLE
images no longer present on wiki page

### ISSUE THREAD

**Issue by michael63-osm** [facebookmicrosites/Open-Mapping-At-Facebook#22]
**Images no longer present on wiki page**

#
**Description:**

https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki just shows the text, the images are no longer visible. Using a snapshot from the wayback machine currently is the only option to see the complete document.

**Comment by tsmock** [comment]
Fixed in https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Home/df1cf4210d604eb6b784a475e69fe8c2a10456e1.
