### ISSUE TITLE
turkiye/ syria update request

### ISSUE THREAD

**Issue by justinelliotmeyers** [facebookmicrosites/Open-Mapping-At-Facebook#24]
could we get a fresh set of roads from the latest imagery?

**Comment by justinelliotmeyers** [comment]
@tsmock Is there new imagery/ ai roads that can be created for TR/ SY? Thank you

**Comment by tsmock** [comment]
At this time, I don't believe so. I'll check, but our recent focus has been getting local governments to open up their data for [OpenStreetMap](https://www.openstreetmap.org) (through Esri).
