### ISSUE TITLE
Possible Malware

### ISSUE THREAD

**Issue by andreweryan** [facebookmicrosites/Open-Mapping-At-Facebook#25]
Hello, I downloaded several files just now and Windows defender flagged the following files as a Trojan:Script/Wacatac.H!ml threat:

CO_mapwithai_road_data.gpkg.tar.gz
VE_mapwithai_road_data.gpkg.tar.gz
PE_mapwithai_road_data.gpkg.tar.gz

![threat](https://user-images.githubusercontent.com/9055736/228632744-26a860ae-2667-4b0f-afca-24d1c71afdf3.PNG)

**Comment by tsmock** [comment]
I wasn't able to reproduce using Microsoft Defender on Mac.
`Security intelligence version: 1.385.1495.0` (created on 2023-03-29T12:48:27Z).

You did download the data from https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries right?

**Comment by andreweryan** [comment]
Yes, I downloaded from that link. I downloaded 6-8 files and Defender was raising those errors for 3 of the files I downloaded. I can try to download one again and see if it tries to block it again.

**Comment by tsmock** [comment]
You can try doing that, but maybe the MS Defender definitions are out of date on your machine?

**Comment by andreweryan** [comment]
I have the Security intelligence version: 1.385.1495.0 as well. I downloaded each of the 3 files again and 2 seem fine now but Defender is blocking and quarantining the Peru file immediately after download

**Comment by andreweryan** [comment]
I just downloaded the same file on my laptop and Defender did not find any threats... I guess its possible that Defender on my desktop is throwing a false positive for some reason. I'm closing this issue for now since it appears to be fine. Sorry for the scare!
