### ISSUE TITLE
support

### ISSUE THREAD

**Issue by justinelliotmeyers** [facebookmicrosites/Open-Mapping-At-Facebook#26]
is there still support for these?

**Comment by tsmock** [comment]
Can you please define "support"? I'm going to go through some of the various "support" questions I can think of, but that doesn't necessarily mean that you will get an answer to the question that you _meant_ to ask.

* Do we support AI roads in editors?
  * Yes. Use [Rapid](https://mapwith.ai/rapid) or [JOSM](https://josm.openstreetmap.de) with the MapWithAI plugin.
* Do we still offer AI road downloads?
  * Yes. See [Available Countries](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries).
* Have we run AI road predictions in the last &lt;random period of time&gt;?
  * IIRC, they were last ran them in 2020, which is "good enough" for most areas, not so good for areas under construction (e.g. new residential developments, intersection changes, etc.). If you are looking for areas that need more roads mapped, [Kontur](https://disaster.ninja/active/?map=2.027/-1.551/-30.692&app=58851b50-9574-4aec-a3a6-425fa18dcb54&event=94c409a7-13ff-4eeb-9973-516fdf36e40f&feed=kontur-public&layers=activeContributors%2ChotProjects_outlines%2Ckontur_lines%2CBIV__Kontur+OpenStreetMap+Road+Completeness) made a map that shows where there are many missing roads.

**Comment by justinelliotmeyers** [comment]
Thanks for the response. I just wanted to create an issue to see if there was support for the repo still as I created issues previously and there was no response. I'll ping in the issues themselves to see if there will be answers or if I should just delete as well. Thanks.
