### ISSUE TITLE
Download links dead?

### ISSUE THREAD

**Issue by iboates** [facebookmicrosites/Open-Mapping-At-Facebook#28]
All of the links at https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries are now redirecting to another page. Are these files gone for good? Or is it just a mistake?

**Comment by tsmock** [comment]
I believe this is a mistake.

@Bonkles : I think this might be a result of migrating to https://rapideditor.org/ .

**Comment by iboates** [comment]
@tsmock @Bonkles Is there any update on this?

**Comment by Bonkles** [comment]
I aim to get this done today by EOD. Thanks for the ping! Will update when I think it should be back up.

**Comment by Bonkles** [comment]
This should be fixed now! @iboates please let me know if you are unable to download the files. I was able to download several successfully just now.

**Comment by Bonkles** [comment]
P.S. @iboates The Demo is my fave TF2 guy.

**Comment by iboates** [comment]
@Bonkles i wasnt the man i was id kiss ya

**Comment by iboates** [comment]
(also links seem to work now)
