### ISSUE TITLE
Clarify license of geometry data dumps?

### ISSUE THREAD

**Issue by iandees** [facebookmicrosites/Open-Mapping-At-Facebook#4]
Thanks for releasing the [country-sized geopackage](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries) versions of the detected roads datasets.

Can you add license information to that wiki page? The [repository's readme](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook#license) says MIT license, but I thought I'd double-check

**Comment by jeffdefacto** [comment]
Hi @iandees 

Yes, the data is under the same MIT License. I added a link to it on the page to help clarify it.

Thanks for the suggestion

**Comment by jeffdefacto** [comment]
Additionally, we've added the license to the files themselves now.
