### ISSUE TITLE
In waterways flow direction could Not be changed

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookmicrosites/Open-Mapping-At-Facebook#6]
**Title:** Title of the issue here
In waterways flow direction could Not be changed

#
**Files:** 

List the files related to this issue

#
**Description:**

I am not Sure if the RapiD issues are solved here, but once used the feature and tagged as waterways the flow direction of the water Could Not be changed (Normally V key in ID, but does not work in RapiD).

Thanks. JJ

**Comment by jeffdefacto** [comment]
Hey jjiglesiasg, 

I wasn't able to reproduce this behavior. Do you mind trying again and seeing if it is still happening for you?

If so, please file an issue at the main RapiD github and we'll do some investigation. 
https://github.com/facebookincubator/RapiD/issues

Thanks,
Jeff

**Comment by jjiglesiasg** [comment]
Hi Jeff, yes it keep not changing the flow direction in any waterway produced by RapiD

**Comment by jeffdefacto** [comment]
Ok, thanks for making an issue on the RapiD repo. Closing this duplicate
