### ISSUE TITLE
Isn't the data licence ODbL?

### ISSUE THREAD

**Issue by rory** [facebookmicrosites/Open-Mapping-At-Facebook#7]
There is a [download page with the results of the AI dataset](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/Available-Countries), and it claims the data is [MIT licenced](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/blob/master/LICENSE.md).

But since the dataset is based on OpenStreetMap data (_“only the AI predicted roads that are missing from OpenStreetMap”_), wouldn't this be a derived database, and hence ODbL licenced?

**Comment by danil-kirsanov** [comment]
We are extracting the data from Maxar satellite images (you can learn about all the details from our publications) and our legal team believes this is the correct license. I am not planning to comment on the legal issues further; thank you for your curiosity.

**Comment by matkoniecz** [comment]
> We are extracting the data from Maxar satellite images

And OSM data - note "roads that are missing from OpenStreetMap" part.

**Comment by danil-kirsanov** [comment]
I hope you can enjoy the data despite not liking the license. Locking the thread.
