### ISSUE TITLE
Clarify misleading "Firefox blocks Facebook urls by default"

### ISSUE THREAD

**Issue by matkoniecz** [facebookmicrosites/Open-Mapping-At-Facebook#9]
**Title:** Clarify misleading "Firefox blocks Facebook urls by default"

#
**Files:** 

https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki#firefox-issues

#
**Description:**

"Firefox blocks Facebook urls by default" is misleading, Firefox is not blocking all Facebook urls, only tracking ones. For example Facebook still works in Firefox.

It should be "Firefox blocks Facebook tracking by default" and should make clear that following this instructions stops one of protections against Facebook spying.

**Comment by jeffdefacto** [comment]
This was the result of using facebook.com endpoints for the roads and imagery.

The next version of RapiD will use mapwith.ai end points and resolve the issue.
